=== Mangopay/docs/nethone/notifications/schemas/request_alert.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "minimum": 1,
      "maximum": 9223372036854775807,
      "description": "ID of the notification in Nethone system."
    },
    "type": {
      "type": "string",
      "description": "Type of notification",
      "enum": ["PING", "CASE_CLOSED", "TRANSACTION_ALERT"]
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "description": "Timestamp of the notification",
      "examples": ["2020-11-19T04:54:29Z", "2021-03-23T17:01:00Z"]
    },
    "body": {
      "allOf": [
        { "$ref": "request_alert_body.json" },
        {
          "description": "Notification data"
        }
      ]
    }
  },
  "required": ["id", "type", "created_at", "body"]
}

=== Mangopay/docs/nethone/notifications/examples/alert_transaction_fraud.json
{
  "id": 185459234,
  "type": "TRANSACTION_ALERT",
  "created_at": "2021-03-23T16:01:00Z",
  "body": {
    "alert_type": "fraud",
    "is_3d_secure": false,
    "arn": "123456789",
    "bin_number": "234567",
    "number_last4": "2345",
    "billing_descriptor": "SOME SERVICE",
    "transaction_value": {
      "amount": 11211,
      "amount_decimal": "112.11",
      "currency": "USD"
    },
    "refund_value": {
      "amount": 11211,
      "amount_decimal": "112.11",
      "currency": "USD"
    },
    "transaction_timestamp": "2021-03-25T00:00:00Z",
    "alert_timestamp": "2021-05-02T00:00:00Z",
    "transaction_id": 12345678,
    "transaction_reference": "fraud_txn_unique_ref",
    "merchant_reference": "234567",
    "issuer": "Bank ABC",
    "authorization_code": "123456",
    "reason_code": "4840",
    "source": 2,
    "source_id": "127327139872"
  }
}

=== Mangopay/docs/nethone/notifications/examples/alert_transaction_dispute.json
{
  "id": 185459234,
  "type": "TRANSACTION_ALERT",
  "created_at": "2021-03-23T16:01:00Z",
  "body": {
    "alert_type": "dispute",
    "is_3d_secure": null,
    "arn": "1122334455667788",
    "bin_number": "123456",
    "number_last4": "1234",
    "billing_descriptor": "MY ONLINE SERVICE 123*",
    "transaction_value": {
      "amount": 2345,
      "amount_decimal": "23.45",
      "currency": "EUR"
    },
    "refund_value": {
      "amount": 2345,
      "amount_decimal": "23.45",
      "currency": "EUR"
    },
    "transaction_timestamp": "2021-03-20T11:01:00Z",
    "alert_timestamp": "2021-03-23T15:55:00Z",
    "transaction_id": 11122233444,
    "transaction_reference": "txn_unique_reference",
    "merchant_reference": "123456",
    "issuer": "Bank ABC",
    "authorization_code": "123456",
    "reason_code": "13.3",
    "source": 1,
    "source_id": "ABCBNM123456ZXC"
  }
}
