=== Mangopay/docs/nethone/kyc_authologic/schemas/request_conversation.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["query", "returnUrl", "userKey"],
  "properties": {
    "userKey": {
      "maxLength": 200,
      "minLength": 1,
      "type": "string",
      "description": "Specifies the user you want to check. Authologic remembers this field, returns its value, but Authologic doesn't use the value of this field. Place there the user ID which is used in your system, it will make it easier for you to associate the conversation with the user.",
      "example": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6"
    },
    "returnUrl": {
      "type": "string",
      "description": "The address on your system where the user will be redirected after verifying their identity. If {conversationId} part was given, it will be replaced with the conversation ID.",
      "example": "https://authologic.com/tests/return/?conversation={conversationId}"
    },
    "callback": {
      "type": "string",
      "description": "If a callback address was specified when creating a conversation, it will be called when data is collected. If the address contains the string `{conversationId}`, it will be replaced with the current conversation ID. The content of the call is exactly the same as the response with the details of the conversation. You can read more about callback in <a href='/docs/integration_guide/kyc/callback_mechanism/'>callback mechanism</a> section.",
      "example": "https://system.acme.test/private/identity/callback"
    },
    "layoutUrl": {
      "type": "string",
      "description": "If the process requires multiple redirection of the user to external websites (e.g. logging in to a bank), Authologic must know how to pass control to the place where subsequent pages will be rendered. For this purpose, when creating a conversation, the `layoutUrl` parameter should be specified. The user will be redirected there if there is a need to view further pages. If the address contains the string `{conversationId}`, it will be replaced with the current conversation ID.",
      "example": "https://authologic.com/tests/layout/?conversation={conversationId}"
    },
    "strategy": {
      "type": "string",
      "description": "Information on how Authologic should perform the verification. This field is optional. If not specified, the system will use the default value. In our case, we used the `public:sandbox` strategy, which does not perform real verification, but allows you to select the result, which is convenient for implementation and integration tests. You can read more about strategies in <a href='/docs/integration_guide/kyc/strategies/'>strategies</a> section.",
      "example": "public:default",
      "default": "public:default"
    },
    "query": {
      "$ref": "common/product_query.json"
    },
    "hints": {
      "$ref": "common/product_hints.json"
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/response_conversation_deprecated_query_fields_old.json
{
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "returnUrl": "https://authologic.com/tests/return/?conversation={conversationId}",
  "strategy": "public:default",
  "query": {
    "identity": {
      "fields": {
        "mandatory": ["PERSON_NAME_FIRSTNAME", "PERSON_NAME_LASTNAME"]
      },
      "optional": ["PERSON_CONTACT_EMAIL", "PERSON_IDS_NATIONAL_ID", "PERSON_IDS_PASSPORT_ID"]
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/request_conversation_deprecated_hints_field.json
{
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "returnUrl": "https://authologic.com/tests/return/?conversation={conversationId}",
  "callback": "https://system.acme.test/private/identity/{conversationId}/callback",
  "query": {
    "identity": {
      "requireOneOf": [["PERSON_CONTACT_EMAIL", "PERSON_CONTACT_PHONE"]]
    }
  },
  "hints": {
    "uncertain": {
      "person": {
        "contact": {
          "email": "jan.kowalski@email.com",
          "phone": "+4811111111"
        }
      }
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/response_conversation_deprecated_query_fields_new.json
{
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "returnUrl": "https://authologic.com/tests/return/?conversation={conversationId}",
  "strategy": "public:default",
  "query": {
    "identity": {
      "requireOneOf": [["PERSON_NAME_FIRSTNAME", "PERSON_NAME_LASTNAME"]],
      "optional": [
        {
          "list": ["PERSON_IDS_NATIONAL_ID", "PERSON_IDS_PASSPORT_ID", "PERSON_CONTACT_EMAIL"]
        }
      ]
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/response_conversation_deprecated_query_fields_new_alt.json
{
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "returnUrl": "https://authologic.com/tests/return/?conversation={conversationId}",
  "strategy": "public:default",
  "query": {
    "identity": {
      "requireOneOf": [
        ["PERSON_NAME_FIRSTNAME", "PERSON_NAME_LASTNAME", "PERSON_IDS_NATIONAL_ID"],
        ["PERSON_NAME_FIRSTNAME", "PERSON_NAME_LASTNAME", "PERSON_IDS_PASSPORT_ID"]
      ],
      "optional": [
        {
          "list": ["PERSON_CONTACT_EMAIL"]
        }
      ]
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/request_conversation_strategy_public_ig_iaml.json
{
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "returnUrl": "https://authologic.com/tests/return/?conversation={conversationId}",
  "callback": "https://system.acme.test/private/identity/{conversationId}/callback",
  "strategy": "public:ig+iaml",
  "query": {
    "identity": {
      "requireOneOf": [
        ["PERSON_NAME_FIRSTNAME", "PERSON_NAME_LASTNAME", "PERSON_IDS_NATIONAL_ID"],
        ["PERSON_NAME_FIRSTNAME", "PERSON_NAME_LASTNAME", "PERSON_IDS_PASSPORT_ID"]
      ]
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/request_conversation_extended.json
{
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "returnUrl": "https://authologic.com/tests/return/?conversation={conversationId}",
  "callback": "https://system.acme.test/private/identity/{conversationId}/callback",
  "strategy": "public:default",
  "query": {
    "identity": {
      "requireOneOf": [["PERSON_NAME_FIRSTNAME", "PERSON_NAME_LASTNAME"]],
      "optional": [
        {
          "list": ["PERSON_NAME_FIRSTNAME", "PERSON_NAME_LASTNAME"]
        }
      ]
    },
    "verify": {
      "user": {
        "company": {
          "name": {
            "name": "ACME Inc."
          },
          "ids": {
            "taxId": "1234567890",
            "additionalId": "0987654321"
          },
          "address": {
            "text": "ul. Wiśniowa 133/20 00-950 Warszawa PL",
            "addressLine": "ul. Wiśniowa 133/20",
            "postalCode": "00-950",
            "city": "Warszawa"
          },
          "contact": {
            "email": "jan.kowalski@email.com",
            "phone": "+48692887345"
          }
        },
        "person": {
          "name": {
            "firstName": "Jan",
            "lastName": "Kowalski",
            "middleName": "Stanisław",
            "middleInitial": "S",
            "fullName": "Jan Stanisław Kowalski"
          },
          "ids": {
            "nationalId": "73121243192",
            "idCard": {
              "id": "ABC 12343",
              "issueDate": "2020-11-13",
              "expiryDate": "2020-11-13",
              "issueCountry": "PL"
            },
            "passport": {
              "id": "AD 24243423",
              "issueDate": "2020-11-13",
              "expiryDate": "2020-11-13",
              "issueCountry": "PL"
            },
            "driverLicence": {
              "id": "AA 12343454",
              "issueDate": "2020-11-13",
              "expiryDate": "2020-11-13",
              "issueCountry": "PL"
            },
            "residencePermit": {
              "id": "ZZ 12343454",
              "issueDate": "2020-11-13",
              "expiryDate": "2023-11-13",
              "issueCountry": "PL"
            },
            "otherDocument": {
              "id": "AA 12343454",
              "description": "Document ID.",
              "issueDate": "2022-05-30",
              "expiryDate": "2022-05-30",
              "issueCountry": "GB"
            },
            "accounts": [
              {
                "swiftbic": "BREXPLPW",
                "iban": "PL27114020040000300201355387",
                "currency": "PLN"
              }
            ],
            "cryptoWalletAddresses": [
              {
                "address": "0x3199962acffF2cD9f4a180D53Ddfa36f39F1A432",
                "chainId": "137",
                "name": "matic"
              }
            ]
          },
          "info": {
            "gender": "MALE",
            "nationality": "PL",
            "birthDate": "2020-11-13",
            "birthCity": "Gdańsk"
          },
          "address": {
            "text": "ul. Wiśniowa 133/20 00-950 Warszawa PL",
            "addressLine": "ul. Wiśniowa 133/20",
            "postalCode": "00-950",
            "city": "Warszawa"
          },
          "contact": {
            "email": "jan.kowalski@email.com",
            "phone": "+48692887345"
          }
        }
      }
    },
    "bankTransactions": {
      "type": "ALL",
      "flags": ["INCLUDE_SCHEDULED", "INCLUDE_TAGS"]
    }
  },
  "hints": {
    "userType": "PERSON",
    "known": {
      "company": {
        "name": {
          "name": "ACME Inc."
        },
        "ids": {
          "taxId": "1234567890",
          "additionalId": "0987654321"
        },
        "address": {
          "text": "ul. Wiśniowa 133/20 00-950 Warszawa PL",
          "addressLine": "ul. Wiśniowa 133/20",
          "postalCode": "00-950",
          "city": "Warszawa"
        },
        "contact": {
          "email": "jan.kowalski@email.com",
          "phone": "+48692887345"
        }
      },
      "person": {
        "name": {
          "firstName": "Jan",
          "lastName": "Kowalski",
          "middleName": "Stanisław",
          "middleInitial": "S",
          "fullName": "Jan Stanisław Kowalski"
        },
        "ids": {
          "nationalId": "73121243192",
          "idCard": {
            "id": "ABC 12343",
            "issueDate": "2020-11-13",
            "expiryDate": "2020-11-13",
            "issueCountry": "PL"
          },
          "passport": {
            "id": "AD 24243423",
            "issueDate": "2020-11-13",
            "expiryDate": "2020-11-13",
            "issueCountry": "PL"
          },
          "driverLicence": {
            "id": "AA 12343454",
            "issueDate": "2020-11-13",
            "expiryDate": "2020-11-13",
            "issueCountry": "PL"
          },
          "residencePermit": {
            "id": "ZZ 12343454",
            "issueDate": "2021-11-13",
            "expiryDate": "2023-11-13",
            "issueCountry": "PL"
          },
          "otherDocument": {
            "id": "AA 12343454",
            "description": "Document ID.",
            "issueDate": "2022-05-30",
            "expiryDate": "2022-05-30",
            "issueCountry": "GB"
          },
          "accounts": [
            {
              "swiftbic": "BREXPLPW",
              "iban": "PL27114020040000300201355387",
              "currency": "PLN"
            }
          ],
          "cryptoWalletAddresses": [
            {
              "address": "0x3199962acffF2cD9f4a180D53Ddfa36f39F1A432",
              "chainId": "137",
              "name": "matic"
            }
          ]
        },
        "info": {
          "gender": "MALE",
          "nationality": "PL",
          "birthDate": "2020-11-13",
          "birthCity": "Gdańsk"
        },
        "address": {
          "text": "ul. Wiśniowa 133/20 00-950 Warszawa PL",
          "addressLine": "ul. Wiśniowa 133/20",
          "postalCode": "00-950",
          "city": "Warszawa"
        },
        "contact": {
          "email": "jan.kowalski@email.com",
          "phone": "+48692887345"
        }
      }
    },
    "uncertain": {
      "company": {
        "name": {
          "name": "ACME Inc."
        },
        "ids": {
          "taxId": "1234567890",
          "additionalId": "0987654321"
        },
        "address": {
          "text": "ul. Wiśniowa 133/20 00-950 Warszawa PL",
          "addressLine": "ul. Wiśniowa 133/20",
          "postalCode": "00-950",
          "city": "Warszawa"
        },
        "contact": {
          "email": "jan.kowalski@email.com",
          "phone": "+48692887345"
        }
      },
      "person": {
        "name": {
          "firstName": "Jan",
          "lastName": "Kowalski",
          "middleInitial": "S",
          "fullName": "Jan Stanisław Kowalski"
        },
        "ids": {
          "nationalId": "73121243192",
          "accounts": [
            {
              "swiftbic": "BREXPLPW",
              "iban": "PL27114020040000300201355387",
              "currency": "PLN"
            }
          ],
          "cryptoWalletAddresses": [
            {
              "address": "0x3199962acffF2cD9f4a180D53Ddfa36f39F1A432",
              "chainId": "137",
              "name": "matic"
            }
          ]
        },
        "address": {
          "text": "ul. Wiśniowa 133/20 00-950 Warszawa PL",
          "addressLine": "ul. Wiśniowa 133/20",
          "postalCode": "00-950",
          "city": "Warszawa"
        },
        "contact": {
          "email": "jan.kowalski@email.com",
          "phone": "+48692887345"
        }
      }
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/request_conversation_strategy_public_mme.json
{
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "returnUrl": "https://authologic.com/tests/return/?conversation={conversationId}",
  "callback": "https://system.acme.test/private/identity/{conversationId}/callback",
  "strategy": "public:mme",
  "query": {
    "identity": {
      "requireOneOf": [
        [
          "PERSON_NAME_FIRSTNAME",
          "PERSON_NAME_LASTNAME",
          "PERSON_INFO_BIRTHDATE",
          "PERSON_INFO_NATIONALITY"
        ]
      ]
    },
    "aml": {
      "checks": ["PEP"]
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/request_conversation_strategy_public_sss_document.json
{
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "returnUrl": "https://authologic.com/tests/return/?conversation={conversationId}",
  "callback": "https://system.acme.test/private/identity/{conversationId}/callback",
  "strategy": "public:sss",
  "query": {
    "identity": {
      "requireOneOf": [
        [
          "PERSON_NAME_FIRSTNAME",
          "PERSON_NAME_LASTNAME",
          "PERSON_IDS_NATIONAL_ID",
          "PERSON_INFO_BIRTHDATE"
        ]
      ],
      "optional": [
        {
          "list": [
            "PERSON_IDS_IDCARD_ID",
            "PERSON_IDS_IDCARD_ISSUE_DATE",
            "PERSON_IDS_IDCARD_EXPIRY_DATE",
            "PERSON_IDS_IDCARD_ISSUE_COUNTRY",
            "PERSON_IDS_PASSPORT_ID",
            "PERSON_IDS_PASSPORT_ISSUE_DATE",
            "PERSON_IDS_PASSPORT_EXPIRY_DATE",
            "PERSON_IDS_PASSPORT_ISSUE_COUNTRY",
            "PERSON_IDS_DRIVER_LICENCE_ID",
            "PERSON_IDS_DRIVER_LICENCE_ISSUE_DATE",
            "PERSON_IDS_DRIVER_LICENCE_EXPIRY_DATE",
            "PERSON_IDS_DRIVER_LICENCE_ISSUE_COUNTRY",
            "PERSON_IDS_RESIDENCE_PERMIT_ID",
            "PERSON_IDS_RESIDENCE_PERMIT_ISSUE_DATE",
            "PERSON_IDS_RESIDENCE_PERMIT_EXPIRY_DATE",
            "PERSON_IDS_RESIDENCE_PERMIT_ISSUE_COUNTRY",
            "PERSON_INFO_GENDER",
            "PERSON_INFO_NATIONALITY",
            "PERSON_INFO_BIRTH_CITY"
          ]
        }
      ]
    }
  }
}
