=== Mangopay/docs/nethone/kyc_authologic/schemas/response_conversation.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for the conversation.",
      "example": "e0c0b3cc-8238-414f-9940-9f14bd1b8693"
    },
    "userKey": {
      "type": "string",
      "description": "Unique user identifier in the Customer's system.",
      "example": "d5dbb8e0-192e-4bc6-972c-f7948409d10c"
    },
    "url": {
      "type": "string",
      "description": "Unique web address to which the user should be redirected to verify their identity.",
      "example": "https://authologic.com/tests/return/?conversation={conversationId}"
    },
    "status": {
      "$ref": "common/conversation_status.json"
    },
    "result": {
      "$ref": "common/conversation_result.json"
    },
    "externalLinks": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "description": "Links to 3rd party API that allow to collect data directly from 3rd party API. Available in specific strategies."
      },
      "description": "Links to 3rd party API that allow to collect data directly from 3rd party API. Available in specific strategies."
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/response_conversation_200_multiple_results_partial.json
{
  "id": "c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "url": "https://sandbox.authologic.com/c/c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "status": "FINISHED",
  "result": {
    "identity": {
      "status": "PARTIAL",
      "user": {
        "person": {
          "name": {
            "firstName": "John",
            "lastName": "Doe"
          }
        }
      }
    },
    "bankTransactions": {
      "status": "FAILED"
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/response_conversation_product_bank_transactions.json
{
  "id": "c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "url": "https://sandbox.authologic.com/c/c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "status": "FINISHED",
  "result": {
    "identity": {
      "status": "FINISHED",
      "user": {
        "person": {
          "name": {
            "firstName": "John",
            "lastName": "Doe"
          }
        }
      }
    },
    "bankTransactions": {
      "status": "FINISHED"
    }
  },
  "externalLinks": {
    "api_name": "1e67651e-2d9f-4bce-b36b-f9fa9dc61920"
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/response_conversation_product_data_verification.json
{
  "id": "c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "url": "https://sandbox.authologic.com/c/c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "status": "FINISHED",
  "result": {
    "identity": {
      "status": "FINISHED",
      "user": {
        "person": {
          "name": {
            "firstName": "John",
            "lastName": "Doe"
          }
        }
      }
    },
    "verify": {
      "status": "FINISHED",
      "reliability": 0.6666666666666667,
      "details": [
        {
          "field": "PERSON_NAME_FIRSTNAME",
          "reliability": 0.6666666666666667
        },
        {
          "field": "PERSON_NAME_LASTNAME",
          "reliability": 1
        }
      ]
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/response_conversation_200_in_progress.json
{
  "id": "c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "url": "https://sandbox.authologic.com/c/c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "status": "IN_PROGRESS",
  "result": {
    "identity": {
      "status": "IN_PROGRESS",
      "user": {}
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/response_conversation_deprecated_final_field.json
{
  "id": "c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "url": "https://sandbox.authologic.com/c/c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "status": "CREATED",
  "result": {
    "identity": {
      "status": "IN_PROGRESS",
      "final": false,
      "user": {}
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/response_conversation_product_aml_verification.json
{
  "id": "c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "userKey": "7dfb9ded-c38f-49ae-95e2-307283a0b1f6",
  "url": "https://sandbox.authologic.com/c/c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "status": "FINISHED",
  "result": {
    "identity": {
      "status": "FINISHED",
      "user": {
        "person": {
          "name": {
            "firstName": "John",
            "lastName": "Doe"
          }
        }
      }
    },
    "aml": {
      "status": "FINISHED",
      "found": ["PEP", "SANCTIONS", "ADVERSE_MEDIA"]
    }
  }
}

=== Mangopay/docs/nethone/kyc_authologic/examples/request_callback.json
{
  "id": "e0c0b3cc-8238-414f-9940-9f14bd1b8693",
  "userKey": "d5dbb8e0-192e-4bc6-972c-f7948409d10c",
  "url": "https://sandbox.authologic.com/c/c12c1adc-3ff0-4d32-b95c-c593135c903e",
  "status": "FINISHED",
  "result": {
    "identity": {
      "status": "FINISHED",
      "user": {
        "person": {
          "name": {
            "firstName": "John",
            "lastName": "Doe"
          }
        }
      }
    },
    "verify": {
      "status": "FINISHED",
      "reliability": 0.6666666666666667,
      "details": [
        {
          "field": "PERSON_NAME_FIRSTNAME",
          "reliability": 0.6666666666666667
        },
        {
          "field": "PERSON_NAME_LASTNAME",
          "reliability": 1
        }
      ]
    },
    "bankTransactions": {
      "status": "FINISHED"
    }
  }
}
