=== Mangopay/docs/nethone/inquiries/schemas/items/trip.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Trip",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "const": "trip",
      "description": "Determines the type of Item - for trip items must be a <code>trip</code> string. Do not use <code>trip</code> for flights."
    },
    "id": {
      "type": ["string", "null"],
      "minLength": 1,
      "maxLength": 2048,
      "description": "Identifier of a product, if available"
    },
    "itinerary": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "to": {
            "$ref": "../address.json"
          },
          "from": {
            "$ref": "../address.json"
          },
          "id": {
            "type": ["string", "null"],
            "minLength": 1,
            "maxLength": 2048,
            "description": "Identifier of the trip segment, if available"
          },
          "duration": {
            "type": ["string", "null"],
            "description": "Duration of the trip segment in format 'hours:minutes' or 'hours:minutes:seconds'.",
            "examples": ["01:20", "14:55", "99:59", "123:01:22"],
            "pattern": "^[0-9]{2,}:[0-5][0-9](:[0-5][0-9])?$"
          },
          "distance": {
            "type": ["number", "null"],
            "description": "Distance of the trip segment in kilometers",
            "minimum": 0,
            "examples": [50.25, 120]
          },
          "arrival_datetime": {
            "type": ["string", "null"],
            "format": "date-time",
            "description": "Arrival date and time as in RFC339 section 5.6",
            "examples": ["2020-11-19T04:54:29+02:00"]
          },
          "departure_datetime": {
            "type": ["string", "null"],
            "format": "date-time",
            "description": "Departure date and time as in RFC339 section 5.6",
            "examples": ["2020-11-19T04:54:29+02:00"]
          }
        }
      }
    },
    "refund_policy": {
      "type": ["string", "null"],
      "description": "Refund policy if the trip is cancelled by the customer",
      "enum": ["fully refundable", "partially refundable", "non refundable", null]
    },
    "passengers": {
      "type": "array",
      "description": "A list of passengers on the trip",
      "items": {
        "$ref": "item_person.json"
      }
    },
    "price": {
      "allOf": [
        { "$ref": "../../../common/money.json" },
        {
          "description": "Item's price"
        }
      ]
    },
    "extra_data": {
      "allOf": [
        { "$ref": "../common/extra_data.json" },
        {
          "description": "Additional data associated with this Item (limited to 4kB by default)"
        }
      ]
    }
  },
  "required": ["type"]
}

=== Mangopay/docs/nethone/inquiries/examples/items/trip.json
{
  "price": {
    "amount": "49.99",
    "currency": "EUR"
  },
  "type": "trip",
  "id": "SKJFHDUF123JKL",
  "passengers": [
    {
      "nationality": "US",
      "first_name": "Jason",
      "last_name": "Seagram",
      "gender": "male",
      "document_type": "passport",
      "type": "ADULT",
      "date_of_birth": "1999-02-25"
    },
    {
      "nationality": "GB",
      "first_name": "John",
      "last_name": "Doe",
      "gender": "male",
      "document_type": "passport",
      "type": "ADULT",
      "date_of_birth": "1994-02-14"
    },
    {
      "nationality": "PL",
      "first_name": "Janina",
      "last_name": "Kowalska",
      "gender": "female",
      "document_type": "ID",
      "type": "ADULT",
      "date_of_birth": "2001-02-28"
    }
  ],
  "itinerary": [
    {
      "from": {
        "country": "PL",
        "city": "Warsaw",
        "postal_code": "00-901",
        "street": "plac Defilad",
        "building": "1"
      },
      "to": {
        "country": "PL",
        "city": "Katowice",
        "postal_code": "40-005",
        "street": "al. Wojciecha Korfantego",
        "building": "35"
      },
      "id": "WARKAT000111222",
      "duration": "03:30",
      "distance": 305,
      "departure_datetime": "2022-03-10T08:30:00+02:00",
      "arrival_datetime": "2022-03-10T12:00:00+02:00"
    }
  ],
  "refund_policy": "fully refundable"
}
