=== Mangopay/docs/nethone/lists/schemas/list_of_lists.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "List of lists",
  "additionalProperties": false,
  "type": "object",
  "required": ["page_number", "page_size", "objects_count", "objects"],
  "properties": {
    "page_number": {
      "type": "number",
      "description": "Page number",
      "examples": [1]
    },
    "page_size": {
      "type": "number",
      "description": "Page size",
      "examples": [10]
    },
    "objects_count": {
      "type": "number",
      "description": "Total number of lists in application",
      "examples": [45]
    },
    "objects": {
      "type": "array",
      "description": "Returned lists matching criteria",
      "items": {
        "$ref": "./post_list_response.json"
      }
    }
  }
}

=== Mangopay/docs/nethone/lists/examples/list_of_lists_200.json
{
  "page_number": 1,
  "page_size": 25,
  "objects_count": 3,
  "objects": [
    {
      "id": 1,
      "id_str": "1",
      "name": "accept_list_1",
      "applications": [
        {
          "application_id": 1,
          "application_id_str": "1",
          "access": "restricted",
          "attached_rules": {
            "skip": 0,
            "overriding_accept": 0,
            "refuse": 0,
            "review": 0,
            "accept": 2,
            "trust": 1
          }
        }
      ],
      "display_name": "IP Address & Domain Accept List",
      "active_items_count": 9,
      "expired_items_count": 1,
      "fields": [
        {
          "name": "Accepted IP Address",
          "type": "IP_ADDRESS"
        },
        {
          "name": "Accepted CIDR",
          "type": "CIDR"
        }
      ]
    },
    {
      "id": 2,
      "id_str": "2",
      "name": "refuse_list_1",
      "applications": [
        {
          "application_id": 1,
          "application_id_str": "1",
          "access": "restricted",
          "attached_rules": {
            "skip": 0,
            "overriding_accept": 0,
            "refuse": 2,
            "review": 0,
            "accept": 0,
            "trust": 0
          }
        }
      ],
      "display_name": "Phone No. Refuse List",
      "active_items_count": 215,
      "expired_items_count": 25,
      "fields": [
        {
          "name": "Banned Phone No.",
          "type": "PHONE_NUMBER"
        }
      ]
    },
    {
      "id": 3,
      "id_str": "3",
      "name": "simple_list",
      "applications": [
        {
          "application_id": 1,
          "application_id_str": "1",
          "access": "restricted",
          "attached_rules": {
            "skip": 0,
            "overriding_accept": 0,
            "refuse": 0,
            "review": 3,
            "accept": 0,
            "trust": 0
          }
        }
      ],
      "display_name": "simple_list",
      "active_items_count": 1,
      "expired_items_count": 0,
      "fields": [
        {
          "name": "ISO-3166 Country code",
          "type": "COUNTRY_CODE"
        },
        {
          "name": "ISO-4217 Currency code ",
          "type": "CURRENCY"
        },
        {
          "name": "Accepted Bank Identification Number",
          "type": "BIN"
        }
      ]
    }
  ]
}

=== Mangopay/docs/nethone/lists/examples/item_list_200.json
{
  "page_number": 1,
  "page_size": 25,
  "objects_count": 2,
  "objects": [
    {
      "id": 1,
      "id_str": "1",
      "values": ["PL"],
      "list_id": 4,
      "list_id_str": "4",
      "created_at": "2024-04-11",
      "expires_at": null,
      "expired": false,
      "created_by": {
        "id": 11,
        "id_str": "11",
        "name": "user@example.com"
      },
      "comment": "Added due to our customer fraud policy."
    },
    {
      "id": 2,
      "id_str": "2",
      "values": ["DE"],
      "list_id": 4,
      "list_id_str": "4",
      "created_at": "2023-01-10",
      "expires_at": "2023-11-11",
      "expired": true,
      "created_by": {
        "id": 11,
        "id_str": "11",
        "name": "user@example.com"
      },
      "comment": null
    }
  ]
}
