=== Mangopay/docs/nethone/lists/schemas/post_list_response.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema",
  "required": [
    "id",
    "id_str",
    "name",
    "applications",
    "display_name",
    "active_items_count",
    "expired_items_count",
    "fields"
  ],
  "properties": {
    "id": {
      "type": "number",
      "examples": [1494024],
      "description": "Id of the created list"
    },
    "id_str": {
      "type": "string",
      "description": "Copies the value from corresponding id field as string. Use to avoid JS rounding problems.",
      "examples": ["1494024"]
    },
    "name": {
      "type": "string",
      "description": "Internal name of the list"
    },
    "applications": {
      "type": "array",
      "description": "Applications using this list - it is possible to share list amongst applications",
      "items": {
        "$ref": "./application.json"
      }
    },
    "display_name": {
      "type": "string",
      "description": "Name of the list as displayed in panel"
    },
    "active_items_count": {
      "type": "number",
      "description": "Number of active items on the list"
    },
    "expired_items_count": {
      "type": "number",
      "description": "Number of expired items on the list"
    },
    "fields": {
      "type": "array",
      "description": "Description of fields of the list",
      "items": {
        "$ref": "./common/field_definition.json"
      }
    }
  }
}

=== Mangopay/docs/nethone/lists/examples/post_list_response_200.json
{
  "id": 1,
  "id_str": "1",
  "name": "my_new_list",
  "applications": [
    {
      "application_id": 1,
      "application_id_str": "1",
      "access": "restricted",
      "attached_rules": {
        "skip": 1,
        "overriding_accept": 0,
        "refuse": 0,
        "review": 2,
        "accept": 3,
        "trust": 1
      }
    }
  ],
  "display_name": "My new list",
  "active_items_count": 0,
  "expired_items_count": 0,
  "fields": [
    {
      "name": "User IP Address",
      "type": "IP_ADDRESS"
    }
  ]
}
