=== Mangopay/docs/nethone/inquiries/schemas/response_200.json
{
  "type": "object",
  "description": "desc",
  "$schema": "http://json-schema.org/draft-07/schema",
  "required": ["advice", "id", "id_str", "info"],
  "properties": {
    "id": {
      "type": "integer",
      "description": "Id of created inquiry to reference later - 64 bit value."
    },
    "id_str": {
      "type": "string",
      "description": "Id of created inquiry as string"
    },
    "advice": {
      "type": "string",
      "description": "Recommendation given for the inquiry",
      "enum": ["trust", "accept", "refuse", "review"]
    },
    "info": {
      "type": "object",
      "description": "Additional info for this inquiry",
      "properties": {
        "models": {
          "$ref": "models_node.json"
        },
        "fingerprint": {
          "$ref": "fingerprint/fingerprint.json"
        },
        "rules": {
          "$ref": "rule_results.json"
        },
        "ip_info": {
          "$ref": "ip_info.json"
        }
      }
    }
  }
}

=== Mangopay/docs/nethone/inquiries/examples/response_with_fingerprint_ios.json
{
  "id": 1122334455,
  "id_str": "1122334455",
  "advice": "accept",
  "info": {
    "fingerprint": {
      "signals": [],
      "profiling_type": "ios",
      "attempt_reference": "mznx-012eebc9-36ff-498c-a160-dcc52430bbf0-i",
      "created_date": "2020-08-29 10:12:13.120002",
      "ip": "1.2.3.4",
      "proxied_for_ip": null,
      "device": {
        "battery": {
          "charging": false,
          "level": 35.0,
          "fully_charged": false
        },
        "carrier": {
          "iso_country_code": "pl",
          "mobile_country_code": "260",
          "name": "Carrier",
          "mobile_network_code": "06",
          "allows_voip": true,
          "country": "PL"
        },
        "disk": {
          "total_space": 63978983424.0,
          "free_space": 1234123412.0
        },
        "hardware": {
          "device_model": "iPhone",
          "model": "D211AP",
          "uptime": "1 8 2",
          "device_name": "iPhone",
          "orientation": "portrait",
          "device_system_name": "iOS",
          "device_system_version": "14.8",
          "multitasking_enabled": true,
          "proximity_sensor_enabled": false,
          "device_identifier_for_vendor": "ALFB6KYV-OSNV-PHAY-CKW0-GJJF8JXPTSNX"
        },
        "process_info": {
          "system_version_string": "Version 14.8 (Build 18H17)",
          "processor_count": 6,
          "active_processor_count": 6,
          "physical_memory": "3117711360",
          "low_power_enabled": true
        },
        "bluetooth": null
      },
      "network": {
        "external_ip_address": "1.2.3.4",
        "connected_to_wifi": false,
        "wifi_ip_address": null,
        "connected_to_cell_network": true,
        "cell_ip_address": "11.22.33.44",
        "link_type": "",
        "user_declared_ip": {
          "addr": "1.2.3.4"
        }
      },
      "client": {
        "localization": {
          "country": "pl_PL",
          "currency": "zł",
          "language": "pl-PL",
          "region": "PL",
          "calendar": "gregorian",
          "currency_code": "PLN",
          "metric_system": true,
          "time_zone": "Europe/Warsaw"
        },
        "preference": {
          "preferred_content_size_category": "UICTContentSizeCategoryS",
          "can_send_mail": true,
          "can_send_text": true
        },
        "accessibility": {
          "is_bold_text": false,
          "is_undo_shake": true,
          "is_reduced_motion": false,
          "is_reduced_transparency": false,
          "is_assistive_touch": false,
          "is_darker_system_colors": false,
          "is_switch_control": false,
          "is_voice_over": false,
          "is_mono_audio": false,
          "is_inverted_color": false,
          "is_closed_caption": false,
          "is_grayscale": false,
          "is_video_autoplay": true,
          "is_guided_access": false,
          "is_speak_selection": false,
          "is_speak_screen": false,
          "is_diff_without_color": false,
          "is_switch_label": false
        }
      }
    }
  }
}

=== Mangopay/docs/nethone/inquiries/examples/response_with_fingerprint_android.json
{
  "id": 1122334455,
  "id_str": "1122334455",
  "advice": "accept",
  "info": {
    "fingerprint": {
      "signals": [],
      "profiling_type": "android",
      "attempt_reference": "mznx-3c0a631c-0d7a-40a0-a645-e1910fa2d52a-a",
      "created_date": "2020-08-29 09:11:10.990001",
      "ip": "1.2.3.4",
      "proxied_for_ip": null,
      "network": {
        "link_type": "",
        "user_declared_ip": {
          "addr": "1.2.3.4"
        }
      },
      "device": {
        "carrier": {
          "name": "Carrier",
          "country": "pl",
          "iso_country_code": "pl",
          "mobile_country_code": "260",
          "mobile_network_code": "02",
          "allows_voip": true,
          "icc_card": true,
          "roaming": false,
          "sim_state": 5,
          "radio_phone_type": 1,
          "network_type": null
        },
        "disk": {
          "total_space": "5622530000",
          "free_space_root": "12341234"
        },
        "device": {
          "android_id": "i3u46d5wv6zvg2i5",
          "model": "SM-A715F",
          "manufacturer": "samsung",
          "brand": "samsung",
          "build_fingerprint": "samsung/a71naeea/a71:11/RP1A.200720.012/DHLCUVTT2W4HU:user/release-keys",
          "product": "a71naeea",
          "http_proxy": null,
          "wifi_on": false,
          "bt_on": true,
          "uptime_ms": "587920381"
        },
        "battery": {
          "battery_health": "good",
          "extra_health": 2,
          "level": 50.0,
          "extra_level": 50,
          "extra_scale_level": 100,
          "plugged": "battery",
          "extra_plugged": 0,
          "charging_state": "discharging",
          "extra_status": 3,
          "extra_present": true,
          "extra_technology": "Li-ion",
          "extra_temperature": 349,
          "extra_voltage": 3775
        }
      }
    }
  }
}

=== Mangopay/docs/nethone/inquiries/examples/response_with_rule_results.json
{
  "id": 1122334455,
  "id_str": "1122334455",
  "advice": "refuse",
  "info": {
    "rules": [
      {
        "id": 123456789,
        "id_str": "123456789",
        "name": "BlacklistEmail",
        "advice": "accept",
        "mode": "normal"
      },
      {
        "id": 6543351234,
        "id_str": "6543351234",
        "name": "SameFPCDifferentEmail",
        "advice": "review",
        "mode": "simulation"
      },
      {
        "id": 967895437,
        "id_str": "967895437",
        "name": "FingerprintIpFromDifferentCountries",
        "advice": "refuse",
        "mode": "normal"
      },
      {
        "id": 456789876523,
        "id_str": "456789876523",
        "name": "IPCount",
        "advice": "skip",
        "mode": "normal"
      }
    ]
  }
}

=== Mangopay/docs/nethone/inquiries/examples/response_with_ip_info.json
{
  "id": 1122334455,
  "id_str": "1122334455",
  "advice": "accept",
  "info": {
    "ip_info": {
      "input_ip": {
        "ip": "198.51.100.12",
        "city_name": "Warsaw",
        "country_code": "PL",
        "country_name": "Poland",
        "latitude": 52.2176,
        "longitude": 21.0071,
        "time_zone": "Europe/Warsaw",
        "postal_code": "01-000",
        "autonomous_system_number": 123123,
        "autonomous_system_organization": "Example ASN Org.",
        "isp": "Example ISP"
      },
      "profiler_ip": {
        "ip": "198.51.100.0",
        "city_name": "Warsaw",
        "country_code": "PL",
        "country_name": "Poland",
        "latitude": 52.2176,
        "longitude": 21.0071,
        "time_zone": "Europe/Warsaw",
        "postal_code": "01-000",
        "autonomous_system_number": 123123,
        "autonomous_system_organization": "Example ASN Org.",
        "isp": null
      }
    }
  }
}

=== Mangopay/docs/nethone/inquiries/examples/response_with_models.json
{
  "id": 1122334455,
  "id_str": "1122334455",
  "advice": "refuse",
  "info": {
    "models": [
      {
        "name": "anti-fraud",
        "prediction": {
          "value": 0.4,
          "extra_data": {}
        }
      },
      {
        "name": "customer_segmentation",
        "prediction": {
          "values": {
            "Class A": 0.5,
            "Class B": 0.1,
            "Class C": 0.4
          },
          "extra_data": {}
        }
      },
      {
        "name": "similar_users",
        "prediction": {
          "value": 1.7,
          "extra_data": {
            "most_similar": [
              {
                "references": {
                  "inquiry_id": "1323440692323580514",
                  "attempt_reference": "15698859736366053241569887422",
                  "profiling_reference": "11C64430B4B2DB1A",
                  "user_reference": "12398432423"
                },
                "similarity": 1.5
              },
              {
                "references": {
                  "inquiry_id": "1323440692323580513",
                  "attempt_reference": "15698859736366053241569887421",
                  "profiling_reference": "11A64430B4B2DB1A",
                  "user_reference": "82398432403"
                },
                "similarity": 0.5
              }
            ]
          }
        }
      }
    ]
  }
}

=== Mangopay/docs/nethone/inquiries/examples/response_with_fingerprint_web.json
{
  "id": 1122334455,
  "id_str": "1122334455",
  "advice": "refuse",
  "info": {
    "fingerprint": {
      "signals": ["Keyboard not used"],
      "first_persistent_cookie": "f3ae6977-57fe-4841-bec6-9cb1498bd444",
      "profiling_type": "web",
      "cookie_first_seen": "2020-08-29 10:11:39.096000+00:00",
      "attempt_reference": "54d44064-3c16-40f2-ae05-5b496e082d7d:daef7447-657c-4310-9872-0bb51c5fab3d",
      "created_date": "2020-08-29 11:41:29.570002",
      "ip": "1.2.3.4",
      "proxied_for_ip": null,
      "network": {
        "detected_hops": [
          {
            "addr": "1.2.3.4"
          }
        ],
        "link_type": "",
        "local_ip_addresses": ["0.0.0.0"],
        "user_declared_ip": {
          "addr": "1.2.3.4"
        }
      },
      "client": {
        "cookieEnabled": true,
        "declared": "Chrome",
        "do_not_track": "unknown",
        "entry_point": "https://my.site/order",
        "granular_fingerprint": "064e6b461f5c45a9ab79c260bd321981634cf957",
        "headers": {
          "Host": "TL9M7GYzog.aHjl5eRRqp.com",
          "Accept": "*/*",
          "Cookie": "GYCrYwxCs09MLAFi8uhR=U6etczYsPyV0Fzcs072p5ITUuOA1wbEtyzWqiXHvCNOOF3kcp7urcIffhvPtoNau",
          "Origin": "https://my.site",
          "Referer": "https://my.site/order",
          "Sec-Ch-Ua": "\"Google Chrome\";v=\"95\", \"Chromium\";v=\"95\", \";Not A Brand\";v=\"99\"",
          "User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
          "Content-Type": "",
          "Content-Length": "0",
          "Content_Length": "0",
          "Sec-Fetch-Dest": "empty",
          "Sec-Fetch-Mode": "cors",
          "Sec-Fetch-Site": "cross-site",
          "Accept-Encoding": "gzip, deflate, br",
          "Accept-Language": "pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6",
          "Sec-Ch-Ua-Mobile": "?0",
          "Sec-Ch-Ua-Platform": "\"Windows\""
        },
        "javaEnabled": false,
        "language": "pl-PL",
        "plugins": {
          "NavigatorMimeTypes": {
            "0": {
              "type": "application/pdf",
              "suffixes": "pdf",
              "description": "Portable Document Format",
              "enabledPlugin": {
                "name": "PDF Viewer",
                "length": 2,
                "filename": "internal-pdf-viewer",
                "description": "Portable Document Format"
              }
            },
            "1": {
              "type": "text/pdf",
              "suffixes": "pdf",
              "description": "Portable Document Format",
              "enabledPlugin": {
                "name": "PDF Viewer",
                "length": 2,
                "filename": "internal-pdf-viewer",
                "description": "Portable Document Format"
              }
            }
          },
          "NavigatorPlugins": {
            "0": {
              "name": "PDF Viewer",
              "length": 2,
              "filename": "internal-pdf-viewer",
              "description": "Portable Document Format"
            },
            "1": {
              "name": "Chrome PDF Viewer",
              "length": 2,
              "filename": "internal-pdf-viewer",
              "description": "Portable Document Format"
            },
            "2": {
              "name": "Chromium PDF Viewer",
              "length": 2,
              "filename": "internal-pdf-viewer",
              "description": "Portable Document Format"
            },
            "3": {
              "name": "Microsoft Edge PDF Viewer",
              "length": 2,
              "filename": "internal-pdf-viewer",
              "description": "Portable Document Format"
            },
            "4": {
              "name": "WebKit built-in PDF",
              "length": 2,
              "filename": "internal-pdf-viewer",
              "description": "Portable Document Format"
            }
          }
        },
        "rendering": "WebKit WebGL",
        "timezone": -60
      },
      "behavior": {
        "clipboard": {
          "data": []
        },
        "fields": [],
        "kb_dwell_time_max": null,
        "kb_dwell_time_mean": null,
        "kb_dwell_time_median": null,
        "kb_dwell_time_min": null,
        "kb_dwell_time_sd": null,
        "kb_flight_time_max": null,
        "kb_flight_time_mean": null,
        "kb_flight_time_median": null,
        "kb_flight_time_min": null,
        "kb_flight_time_sd": null,
        "kb_keys_frequency": null,
        "profiling_time": null,
        "sensor": {
          "motion": {
            "acceleration": {
              "x": null,
              "y": null,
              "z": null
            },
            "accelerationIncludingGravity": {
              "x": null,
              "y": null,
              "z": null
            },
            "action_times": {
              "avg": 0.0,
              "len": 1,
              "max": 0.0,
              "min": 0.0,
              "median": 0.0,
              "std": 0.0
            },
            "event_times": {
              "split": null,
              "split_filtered": null,
              "raw": null,
              "filtered": null
            },
            "pause_times": null,
            "rotationRate": {
              "x": null,
              "y": null,
              "z": null
            },
            "unchanging": {
              "number_of_streaks": 0,
              "longest_streak": 0
            }
          },
          "orientation": {
            "action_times": {
              "avg": 0.0,
              "len": 1,
              "max": 0.0,
              "min": 0.0,
              "median": 0.0,
              "std": 0.0
            },
            "alpha": null,
            "beta": null,
            "event_times": {
              "filtered": null,
              "raw": null,
              "split": null,
              "split_filtered": null
            },
            "gamma": null,
            "pause_times": null,
            "unchanging": {
              "number_of_streaks": 0,
              "longest_streak": 0
            }
          }
        },
        "time_spent_in_hidden": null,
        "time_spent_in_visible": null
      },
      "device": {
        "battery": {
          "level": 1,
          "charging": true,
          "chargingTime": 0,
          "dischargingTime": null
        },
        "concurrency": 4,
        "is_mobile": false,
        "number_of_fonts": 100,
        "os_declared": "Windows",
        "rendering": "ANGLE (NVIDIA, NVIDIA GeForce GT 430 Direct3D11 vs_5_0 ps_5_0, D3D11-23.21.13.8859)",
        "screen": {
          "AvailableResolution": [1360, 728],
          "availableSize": [0, 0],
          "ColorDepth": 24,
          "orientation": {
            "angle": 0,
            "type": "landscape-primary"
          },
          "ScreenResolution": [1360, 768],
          "ViewportSize": [1221, 568],
          "visibility": {
            "hidden": false,
            "visibilityState": "visible"
          },
          "windowSize": {
            "innerHeight": 568,
            "innerWidth": 1236,
            "outerHeight": 728,
            "outerWidth": 1360
          }
        }
      }
    }
  }
}
